language: bash

env:
  - SHUNIT_COLOR='always'

script:
  # Execute the unit tests.
  - ./test_runner

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - ksh
      - zsh

matrix:
  include:
    - os: linux
      script:
        # Run the source through ShellCheck (http://www.shellcheck.net).
        - shellcheck *_test.sh
        - shellcheck -s sh shflags shflags_test_helpers
