version: 2
jobs:
  build:
    docker:
      # - image: buildpack-deps:trusty
      # - image: ruudk/ghostscript
      # - image: ubuntu:latest
      - image: ubuntu:16.04
      # - image: ubuntu:14.04
      # - image: centos:latest
      # - image: debian:stable

    working_directory: ~/csm-marks

    steps:
      - checkout

      - run:
          name: Install tools
          command: |
            apt-get -y update
            apt-get -y install wget gnupg
            apt-get -y install curl
            apt-get -y install apt-transport-https
            curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
            curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | tee /etc/apt/sources.list.d/microsoft.list
            apt-get -y update
            apt-get -y install make
            apt-get -y install powershell
            apt-get -y install ghostscript
            make --version

      - run:
          name: Build
          command: make

      # - store_artifacts:
      #     path: sources/stamps/release/test.pdf
